### ISSUE TITLE
Arrows and chevrons - icon choice

### ISSUE THREAD

**Issue by mateuszwilczek** [pmario/lucide-tiddlywiki-plugin#2]
I think we could simply use the Lucide's `chevron-` and `chevrons-` for TW arrows and chevrons. These Lucide icons are smaller, but I think more elegant and consistent with the rest (e.g. the custom fold/unfold icons use a small size of the chevron shape), while at the same time sufficiently readable.

If you want to stay with the custom bigger variants, there is currently an inconsistency, because only the `$:/core/images/down-arrow` uses a custom bigger variant, while the three other arrows use Lucides smaller variants - this is especially apparent using e.g. the toc macro (notice the big down arrows and small right arrows):
![image](https://github.com/user-attachments/assets/8d6e1deb-6e5a-4549-ba9d-1b5b6f917dc1)

**Comment by pmario** [comment]
I did use the "big" down-arrow because of the tiddler toolbar "More" button, which look ridiculous if it is "small" 

The down-arrow is used a lot in the current core UI and I think it does not look good. 
So I personally prefer the little inconsistency in the TOC.

**Demo** [lucide-all-down-arrow.html](https://pmario.github.io/lucide-tiddlywiki-plugin/lucide-all-down-arrow.html#Icon%20Gallery)

@jermolene -- What do you think?

![grafik](https://github.com/user-attachments/assets/02ac3229-2d65-4d11-80c4-89fe70de6a6a)

**Comment by Jermolene** [comment]
> I did use the "big" down-arrow because of the tiddler toolbar "More" button, which look ridiculous if it is "small"

Thanks for putting together the demo. I actually quite like the small version of the down arrow. The disparity in size quite nicely conveys the difference between this and the other toolbar buttons: this button is more like navigation than an action, so it is appropriate that it looks different.

It might be helpful if you could prepare a screenshot of the large version for side-by-side comparison.

**Comment by pmario** [comment]
>It might be helpful if you could prepare a screenshot of the large version for side-by-side comparison.

![grafik](https://github.com/user-attachments/assets/d60ea6d5-5f78-4690-a514-c453c729cf54)

**Comment by pmario** [comment]
As I wrote. For me it looked strange, even after some time I used it. That's why I did change it, which caused the inconsistency in the TOC, which I did not see. 

If you both think the the smaller down arrow looks better, I'm fine with that. I am sure I will would get used to it.

**Comment by pmario** [comment]
The info about the custom-icons can also be found at: https://pmario.github.io/lucide-tiddlywiki-plugin/lucide-all.html#%24%3A%2Fplugins%2Ftiddlywiki%2Flucide-core in the readme tab.

**Comment by Jermolene** [comment]
Thanks @pmario I do think I prefer the smaller arrow for the "more" icon.

**Comment by pmario** [comment]
OK -- We will use it that way

**Comment by pmario** [comment]
latest versions pushed

- https://pmario.github.io/lucide-tiddlywiki-plugin
- https://pmario.github.io/lucide-tiddlywiki-plugin/lucide-all.html
