### ISSUE TITLE
Preview - icon choice

### ISSUE THREAD

**Issue by mateuszwilczek** [pmario/lucide-tiddlywiki-plugin#3]
I would use Lucide `eye-off` ![image](https://github.com/user-attachments/assets/a876f19a-69a1-4936-b8f8-8642411010ba) for `$:/core/images/preview-closed`,
and Lucide `eye` for `$:/core/images/preview-open`.

Right now they are swapped (the closed eyelid shown when preview shown, the eye shown when preview closed), plus the Lucide `eye-closed` looks to me confusing and unclear without proper context (same as the old core icon), I find the crossed-though eye icon much more obvious.

**Comment by pmario** [comment]
See: timer-eye.html -> [Icon Gallery](https://pmario.github.io/lucide-tiddlywiki-plugin/timer-eye.html#Icon%20Gallery:%5B%5BIcon%20Gallery%5D%5D) - from branch `timer`

![grafik](https://github.com/user-attachments/assets/7a3cd005-adea-4809-ae13-229331b3fbdc)

**Comment by pmario** [comment]
latest versions pushed

- https://pmario.github.io/lucide-tiddlywiki-plugin
- https://pmario.github.io/lucide-tiddlywiki-plugin/lucide-all.html
